### ISSUE TITLE
Union[str, Sequence[T]] denies strings

### ISSUE THREAD

**Issue by dahlia** [agronholm/typeguard#11]
`Union[str, Sequence[T]]` (where `T` is not `str`) denies strings:

```python
from typing import Sequence, Union

from typeguard import typechecked


@typechecked
def check_union_sequence(v: Union[str, Sequence[int]]):
    pass


check_union_sequence('test')
```

The last call should pass without `TypeError`, but it actually doesn't:

```pytb
Traceback (most recent call last):
  File "t.py", line 11, in <module>
    check_union_sequence('test')
  File "/Users/dahlia/.virtualenvs/store-service/lib/python3.5/site-packages/typeguard.py", line 450, in wrapper
    check_argument_types(memo)
  File "/Users/dahlia/.virtualenvs/store-service/lib/python3.5/site-packages/typeguard.py", line 419, in check_argument_types
    check_type(description, value, expected_type, memo)
  File "/Users/dahlia/.virtualenvs/store-service/lib/python3.5/site-packages/typeguard.py", line 366, in check_type
    checker_func(argname, value, expected_type, memo)
  File "/Users/dahlia/.virtualenvs/store-service/lib/python3.5/site-packages/typeguard.py", line 204, in check_sequence
    check_type('{}[{}]'.format(argname, i), v, value_type, memo)
  File "/Users/dahlia/.virtualenvs/store-service/lib/python3.5/site-packages/typeguard.py", line 382, in check_type
    format(argname, qualified_name(expected_type), qualified_name(value)))
TypeError: type of argument "v"[0] must be int; got str instead
```

**Comment by agronholm** [comment]
I am unable to reproduce this with the latest version. Comment if you disagree.
