### ISSUE TITLE
TypeError when checking Union containing Literal type

### ISSUE THREAD

**Issue by rfrowe** [agronholm/typeguard#113]
When type checking a value against a union containing a literal type, a TypeError is encountered when constructing the correct TypeError message.

## Reproduction
```python3
from typing import Literal, Union
from typeguard import check_type

FooBar = Union[int, Literal['one', 'two', 'three']]
check_type('repro', 'ome', FooBar)
``` 

### Expected
The expected error message here is undefined but should be something like:
```
TypeError: type of repro must be one of (Literal['one', 'two', 'three'], int); got 'ome' instead
```

### Actual
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python3.8/site-packages/typeguard/__init__.py", line 566, in check_type
    checker_func(argname, value, expected_type, memo)
  File ".../python3.8/site-packages/typeguard/__init__.py", line 408, in check_union
    typelist = ', '.join(get_type_name(t) for t in union_params)
TypeError: sequence item 1: expected str instance, NoneType found
```

**Comment by agronholm** [comment]
This happened because `Literal` doesn't have a `__name__` attribute and its `_name` attribute is `None`.

**Comment by rfrowe** [comment]
Haha I totally forgot I ran into this issue in March and made this issue 🤣Guess #128 was a duplicate then
