### ISSUE TITLE
Binary special methods cannot return NotImplemented

### ISSUE THREAD

**Issue by cjolowicz** [agronholm/typeguard#178]
**Describe the bug**
Typeguard raises TypeError when binary special methods (e.g. `__eq__()`, `__lt__()`, `__add__()`, `__rsub__()`, etc.) return [NotImplemented] instead of the declared return type.

[NotImplemented]: https://docs.python.org/3/library/constants.html?highlight=notimplemented#NotImplemented

**To Reproduce**
```python
from typeguard import typechecked

@typechecked
class C:
    value: int = 42

    def __eq__(self, other: object) -> bool:
        if isinstance(other, C):
            return self.value == other.value
        return NotImplemented


if C() == "teapot":
    pass
```

```sh
❯ python repro.py 
Traceback (most recent call last):
  File "/home/cjolowicz/Code/github.com/agronholm/typeguard/.issues/N/repro.py", line 13, in <module>
    if C() == "teapot":
  File "/home/cjolowicz/Code/github.com/agronholm/typeguard/src/typeguard/__init__.py", line 916, in wrapper
    raise TypeError(*exc.args) from None
TypeError: type of the return value must be bool; got NotImplementedType instead
```

**Expected behavior**
It should not raise TypeError.

**Additional context**
The example type-checks in mypy.

The following does type-check fine in typeguard:

```
    def __eq__(self, other: object) -> Union[bool, type(NotImplemented)]:
```

Unfortunately, this does not work with mypy:

```sh
❯ mypy repro.py 
repro.py:9: error: Invalid type comment or annotation
repro.py:9: note: Suggestion: use type[...] instead of type(...)
Found 1 error in 1 file (checked 1 source file)
```

Neither does `type[NotImplemented]`. (That's not surprising because unlike None, NotImplemented cannot be used to designate its own type.).

```sh
repro.py:9: error: Return type "Union[bool, Type[NotImplemented?]]" of "__eq__" incompatible with return type "bool" in supertype "object"
repro.py:9: error: Variable "builtins.NotImplemented" is not valid as a type
repro.py:9: note: See https://mypy.readthedocs.io/en/latest/common_issues.html#variables-vs-type-aliases
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by cjolowicz** [comment]
For reference, in mypy `NotImplemented` has type `Any` to simplify return types on binary special methods:

- https://github.com/python/mypy/issues/363
- https://github.com/python/mypy/issues/6710#issuecomment-485580032

Returning `NotImplemented` in a binary special method declared to return `bool` does not raise `warn-return-any`: 

- https://github.com/python/mypy/blob/master/mypy/checker.py#L3201-L3202

**Comment by brianrodri** [comment]
Sorry if I'm missing something, but I can't find any official guidance or workarounds for this issue.

What should we use?
```python
def __eq__(self, other: Any) -> bool: ... # Doesn't work.
def __eq__(self, other: Any) -> Union[bool, NotImplemented]: ... # Doesn't work.
def __eq__(self, other: Any) -> Any: ... # This, since `NotImplemented is Any`?
```
