### ISSUE TITLE
Error at instrumenting cryptography.utils

### ISSUE THREAD

**Issue by jolaf** [agronholm/typeguard#206]
The following code, that imports all `cryptography` submodules:
```python3
from importlib import import_module
from pkgutil import iter_modules

from typeguard.importhook import install_import_hook

def importSubmodules(path: str, prefix: str) -> None:
    for subModule in iter_modules((path,)):
        subModuleName = f'{prefix}.{subModule.name}'
        subModulePath = f'{path}/{subModule.name}'
        print(subModuleName)
        import_module(subModuleName)
        importSubmodules(subModulePath, subModuleName)

install_import_hook('cryptography')

import cryptography
importSubmodules(cryptography.__path__[0], cryptography.__name__)
```
crashes as follows:
```bash
$ python3 test.py 
cryptography.__about__
cryptography.exceptions
cryptography.fernet
/home/jolaf/.local/lib/python3.8/site-packages/typeguard/__init__.py:910: UserWarning: no type annotations present -- not typechecking cryptography.utils.read_only_property.<locals>.<lambda>
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/home/jolaf/.local/lib/python3.8/site-packages/typeguard/__init__.py:910: UserWarning: no type annotations present -- not typechecking cryptography.utils.read_only_property.<locals>.<lambda>
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/home/jolaf/.local/lib/python3.8/site-packages/typeguard/__init__.py:910: UserWarning: no type annotations present -- not typechecking cryptography.hazmat._oid.ObjectIdentifier._name
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    importSubmodules(cryptography.__path__[0], cryptography.__name__)
  File "test.py", line 11, in importSubmodules
    import_module(subModuleName)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/jolaf/.local/lib/python3.8/site-packages/typeguard/importhook.py", line 81, in exec_module
    return super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jolaf/.local/lib/python3.8/site-packages/cryptography/fernet.py", line 17, in <module>
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/jolaf/.local/lib/python3.8/site-packages/typeguard/importhook.py", line 81, in exec_module
    return super().exec_module(module)
  File "/home/jolaf/.local/lib/python3.8/site-packages/cryptography/hazmat/primitives/ciphers/__init__.py", line 6, in <module>
    from cryptography.hazmat.primitives.ciphers.base import (
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/jolaf/.local/lib/python3.8/site-packages/typeguard/importhook.py", line 81, in exec_module
    return super().exec_module(module)
  File "/home/jolaf/.local/lib/python3.8/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 218, in <module>
    class _AEADEncryptionContext(_AEADCipherContext):
  File "/home/jolaf/.local/lib/python3.8/site-packages/cryptography/utils.py", line 45, in register_decorator
    verify_interface(iface, klass, check_annotations=check_annotations)
  File "/home/jolaf/.local/lib/python3.8/site-packages/cryptography/utils.py", line 90, in verify_interface
    sig = inspect.signature(getattr(iface, method))
  File "/usr/lib/python3.8/inspect.py", line 3105, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/usr/lib/python3.8/inspect.py", line 2854, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "/usr/lib/python3.8/inspect.py", line 2228, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: <property object at 0x7fae8f24fea0> is not a callable object

$ ls -lad /home/user/.local/lib/python3.8/site-packages/typeguard-*
drwxrwxr-x 2 user user 4096 Jun  4 15:32 /home/user/.local/lib/python3.8/site-packages/typeguard-2.12.1.dist-info

$ python3 -c "import cryptography; print(cryptography.__version__)"
3.4.7

$ python3 --version
Python 3.8.10

$ cat /etc/issue
Ubuntu 20.04.3 LTS \n \l

$ uname -a
Linux ubuntu 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
If `install_import_hook()` call is commented out, the test doesn't crash, which makes me think it's a `typeguard` issue.

**Comment by agronholm** [comment]
Do you mean you still get the same error? The `cryptography` module now imports properly with the import hook, but the script produces a different error: `NameError: name '_RegisterDecoratorType' is not defined`. This happens because `cryptography.utils.register_interface()` declares a return type annotation that does not exist at run time: https://github.com/pyca/cryptography/blob/main/src/cryptography/utils.py#L58

So, the original bug is gone. What remains is more of a design issue due to the forward reference policy not being configurable in the import hook. I'll try to find out if this can be worked around in this specific case.

**Comment by jolaf** [comment]
Thanks!!
