### ISSUE TITLE
False positive DeprecatedWarning

### ISSUE THREAD

**Issue by jolaf** [agronholm/typeguard#209]
The following code:
```python3
from typeguard.importhook import install_import_hook

with install_import_hook(('tornado',)):
    import tornado.util
```
produces the following output:
```shell
$ python3 -W all test.py
/usr/lib/python3/dist-packages/tornado/util.py:255: DeprecationWarning: invalid escape sequence \d
  """Unescape a string escaped by `re.escape`.

$ python3 -W error test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    import tornado.util
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/buildmaster/.local/lib/python3.8/site-packages/typeguard/importhook.py", line 81, in exec_module
    return super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "/home/buildmaster/.local/lib/python3.8/site-packages/typeguard/importhook.py", line 71, in source_to_code
    tree = _call_with_frames_removed(compile, source, path, 'exec', ast.PyCF_ONLY_AST,
  File "/home/buildmaster/.local/lib/python3.8/site-packages/typeguard/importhook.py", line 13, in _call_with_frames_removed
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/tornado/util.py", line 255
    """Unescape a string escaped by `re.escape`.
    ^
SyntaxError: invalid escape sequence \d
```
If `with install_import_hook(('tornado',))` is not used, no problem is reported.

It looks like `typeguard` is more strict to code syntax than Python itself, which is probably not a good idea.

Versions used:
```shell
$ python3
Python 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import typeguard
>>> typeguard
<module 'typeguard' from '/home/buildmaster/.local/lib/python3.8/site-packages/typeguard/__init__.py'>

>>> import tornado
>>> tornado.version
'5.1.1'

$ ls -ld /home/buildmaster/.local/lib/python3.8/site-packages/typeguard*
drwxr-xr-x 3 buildmaster users 4096 Oct 11 00:11 /home/buildmaster/.local/lib/python3.8/site-packages/typeguard
drwxr-xr-x 2 buildmaster users 4096 Oct 11 00:11 /home/buildmaster/.local/lib/python3.8/site-packages/typeguard-2.13.0.dist-info

$ uname -a
Linux i-buildcore-01-11 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/issue
Ubuntu 20.04.3 LTS \n \l
```

**Comment by jolaf** [comment]
Could it be those modifications cause a `DeprecationWarning`/`SyntaxError` to occur?

**Comment by jolaf** [comment]
Sorry, my bad, I've found a way to reproduce the problem without `typeguard`:
https://github.com/tornadoweb/tornado/issues/3076

It's a `tornado` issue indeed.
The reason it is not easily reproducible without `typeguard` is that the problem occurs at compilations which normally occurs just once at installation of `tornado`.
