### ISSUE TITLE
Fail to process class name annotation in a nested class

### ISSUE THREAD

**Issue by jolaf** [agronholm/typeguard#211]
The following code:

`TypeGuardTest.py`:
```python3
from typeguard.importhook import install_import_hook
install_import_hook('test')
import test
```
`test.py`:
```python3
from typing import Type, TypeVar

class A:
    def getClass(self) -> 'A':
        return self

T = TypeVar('T')

def extendedClass(Class: Type[T]) -> Type[T]:
    class ExtendedClass(Class):
        def getClass(self) -> 'ExtendedClass':
            print("OK")
            return self
    return ExtendedClass

extendedClass(A)().getClass()
```
produces the following output:
```shell
$ python3 test.py 
OK

$ python3 TypeGuardTest.py 
Traceback (most recent call last):
  File "TypeGuardTest.py", line 3, in <module>
    import test
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/jolaf/.local/lib/python3.8/site-packages/typeguard/importhook.py", line 81, in exec_module
    return super().exec_module(module)
  File "/media/sf_d/WWPass/git/python-test/test.py", line 16, in <module>
    extendedClass(A)().getClass()
  File "/home/jolaf/.local/lib/python3.8/site-packages/typeguard/__init__.py", line 1013, in wrapper
    memo = _CallMemo(python_func, _localns, args=args, kwargs=kwargs)
  File "/home/jolaf/.local/lib/python3.8/site-packages/typeguard/__init__.py", line 193, in __init__
    hints = get_type_hints(func, localns=frame_locals)
  File "/usr/lib/python3.8/typing.py", line 1264, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/usr/lib/python3.8/typing.py", line 270, in _eval_type
    return t._evaluate(globalns, localns)
  File "/usr/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'ExtendedClass' is not defined

$ python3 --version
Python 3.8.10

$ ls -ld /home/user/.local/lib/python3.8/site-packages/typeguard*
drwxrwxr-x 3 jolaf jolaf 4096 Nov  1 18:36 /home/jolaf/.local/lib/python3.8/site-packages/typeguard
drwxrwxr-x 2 jolaf jolaf 4096 Nov  1 18:36 /home/jolaf/.local/lib/python3.8/site-packages/typeguard-2.13.0.dist-info

$ uname -a
Linux ubuntu 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/issue
Ubuntu 20.04.3 LTS \n \l
```

**Comment by agronholm** [comment]
Yeah, it won't be able to type check it but it should not raise a `NameError`.

**Comment by agronholm** [comment]
But wait, is this really a bug or just expected behavior? How, at run time, would it resolve the name `ExtendedClass`?

**Comment by jolaf** [comment]
My idea was if `mypy` is able to resolve in statically, without running any code, than `typeguard` should definitely be able to do it.

If 'getClass()` method is defined, it's defined in some class. That class name should be known, no?

**Comment by agronholm** [comment]
> My idea was if mypy is able to resolve in statically, without running any code, than typeguard should definitely be able to do it.

This assumption is flawed because mypy is a static typechecker while typeguard is a run-time typechecker which relies on information available at run time.

The problem you experienced is very similar to the one that prompted the Python steering council to defer the change that would have made `from __future__ import annotations` the default on Python 3.10.

**Comment by jolaf** [comment]
Well, you definitely know better.

**Comment by agronholm** [comment]
I just pushed changes that made typeguard use the configured forward reference policy here, so it just emits a warning by default.
