### ISSUE TITLE
Import hook is not working with runpy.run_path()

### ISSUE THREAD

**Issue by jolaf** [agronholm/typeguard#212]
The following code:

`TypeGuardTest.py`:
```python3
from runpy import run_module, run_path
from sys import argv

from typeguard.importhook import install_import_hook, TypeguardFinder

class TypeguardAllFinder(TypeguardFinder):
    def should_instrument(self, module_name: str) -> bool:
        return True

install_import_hook('', cls = TypeguardAllFinder)
name = argv[1]
if name.endswith('.py'):
    run_path(name, run_name = '__main__')
else:
    run_module(name, run_name = '__main__')
```
`test.py`:
```python3
def f(x: str) -> None:
    pass
f(5)
print("OK")
```
produces the following output:
```shell
$ python3 test.py 
OK

$ python3 TypeGuardTest.py test
Traceback (most recent call last):
  File "TypeGuardTest.py", line 15, in <module>
    run_module(name, run_name = '__main__')
  File "/usr/lib/python3.8/runpy.py", line 210, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/media/sf_d/WWPass/git/python-test/test.py", line 3, in <module>
    f(5)
  File "/home/jolaf/.local/lib/python3.8/site-packages/typeguard/__init__.py", line 1014, in wrapper
    check_argument_types(memo)
  File "/home/jolaf/.local/lib/python3.8/site-packages/typeguard/__init__.py", line 857, in check_argument_types
    raise TypeError(*exc.args) from None
TypeError: type of argument "x" must be str; got int instead

$ python3 TypeGuardTest.py test.py
OK

$ python3 --version
Python 3.8.10

$ ls -ld /home/user/.local/lib/python3.8/site-packages/typeguard*
drwxrwxr-x 3 jolaf jolaf 4096 Nov  1 18:36 /home/jolaf/.local/lib/python3.8/site-packages/typeguard
drwxrwxr-x 2 jolaf jolaf 4096 Nov  1 18:36 /home/jolaf/.local/lib/python3.8/site-packages/typeguard-2.13.0.dist-info

$ uname -a
Linux ubuntu 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64()` x86_64 x86_64 GNU/Linux

$ cat /etc/issue
Ubuntu 20.04.3 LTS \n \l
```
As you can see, if `test.py` is imported as a module with `run_module()`, typeguard kicks in successfully and detects a typing error. But if the same `test.py` is imported as a file with `run_path()`, typeguard import hook gets bypassed, the imported module is not instrumented and no typing error is detected.

This issue limits the ability of using typeguard as a command line tool to launch and check existing Python scripts and applications.

**Comment by agronholm** [comment]
Are you sure that `run_path()` doesn't just run it in a subprocess? Nothing typeguard could do if that is the case.

**Comment by jolaf** [comment]
I'm positively sure, because if `test.py` imports any other modules, they do get instrumented and checked properly.
The only module that misses instrumentation is `test.py` itself.

**Comment by agronholm** [comment]
It seems that `runpy.run_path()` completely bypasses the import system so the import hook is useless with it.
