### ISSUE TITLE
StopIteration on checking empty lists on master

### ISSUE THREAD

**Issue by supersergiy** [agronholm/typeguard#287]
**Describe the bug**
`typeguard` master throws `StopIteration` on checking empty lists.
This problem does not occur with the `pypi` release version.

**To Reproduce**
```python
from typeguard import typechecked

@typechecked
def foo() -> list[int]:
    return []

foo()
```

```
Traceback (most recent call last):
  File "/home/sergiy/tmp/type_adventures/bug_x0.py", line 9, in <module>
    foo()
  File "/mnt/disks/sergiy-x0/code/typeguard/src/typeguard/_decorators.py", line 138, in wrapper
    check_return_type(retval, memo)
  File "/mnt/disks/sergiy-x0/code/typeguard/src/typeguard/_functions.py", line 203, in check_return_type
    check_type_internal(retval, annotation, memo)
  File "/mnt/disks/sergiy-x0/code/typeguard/src/typeguard/_checkers.py", line 655, in check_type_internal
    checker(value, origin_type, args, memo)
  File "/mnt/disks/sergiy-x0/code/typeguard/src/typeguard/_checkers.py", line 265, in check_list
    samples = memo.config.collection_check_strategy.iterate_samples(value)
  File "/mnt/disks/sergiy-x0/code/typeguard/src/typeguard/_config.py", line 53, in iterate_samples
    return [next(iter(iterable))]
StopIteration
```

**Comment by agronholm** [comment]
Ah, I see what's going on. Curious that the test suite didn't catch this.
