### ISSUE TITLE
3.0.0 version typechecked bug for lists

### ISSUE THREAD

**Issue by Jonas1312** [agronholm/typeguard#312]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

3.0.0

### Python version

3.7

### What happened?

Hi,

First, thanks a lot for your library, really helps!

Today, I updated typeguard from 2.13.3 to 3.0.0 and my code doesn't work anymore.

Downgrading to 2.13.3 works.

bug:
```python
Traceback (most recent call last):
  File "/Users/jonasm/kili-python-sdk/mre_typeguard.py", line 22, in <module>
    main()
  File "/Users/jonasm/kili-python-sdk/mre_typeguard.py", line 18, in main
    my_method([1, 2, 3])
  File "/Users/jonasm/kili-python-sdk/mre_typeguard.py", line 13, in my_method
    a, my_list = other_method()
  File "/opt/anaconda3/envs/python37/lib/python3.7/site-packages/typeguard/_functions.py", line 255, in check_variable_assignment
    check_type_internal(value, expected_type, memo)
  File "/opt/anaconda3/envs/python37/lib/python3.7/site-packages/typeguard/_checkers.py", line 667, in check_type_internal
    checker(value, origin_type, args, memo)
  File "/opt/anaconda3/envs/python37/lib/python3.7/site-packages/typeguard/_checkers.py", line 267, in check_list
    raise TypeCheckError("is not a list")
typeguard.TypeCheckError: my_list is not a list
```

Thanks!

### How can we reproduce the bug?

typeguard 3.0.0 
typing-extensions 4.5.0 
Python 3.7

```python
from typing import List
from typeguard import typechecked

def other_method():
    return (None, [1, 2, 3])

@typechecked
def my_method(my_list: List):
    print(my_list)
    a, my_list = other_method()  # crash here
    return a, my_list

def main():
    my_method([1, 2, 3])

if __name__ == "__main__":
    main()

```

**Comment by agronholm** [comment]
There seems to be a bug in Typeguard regarding unpacking assignment. This works:
```python
result = other_method()
a = result[0]
my_list = result[1]
```
