### ISSUE TITLE
ImportError: cannot import name 'TYPE_CHECKING' from typeguard

### ISSUE THREAD

**Issue by a-t-0** [agronholm/typeguard#325]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

3.0.2

### Python version

3.10.9

### What happened?

I had a working code, which contained (MWE): 
```py
from typeguard import TYPE_CHECKING
if TYPE_CHECKING:
    print("Hello world")

@typechecked
def add_two(x:int) -> int:
    """Adds two"""
    return x+2
```

Then I updated `pre-commit`:
```
pre-commit autoupdate
```
and then I received the error message:
```
python -m src.snncompare -e mdsa_long_no_overwrite -j1 -j2 -j4 -rev  -dr
Traceback (most recent call last):
  File "/home/name/miniconda/envs/snncompare/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/name/miniconda/envs/snncompare/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/name/git/snn/snncompare/src/snncompare/__main__.py", line 4, in <module>
    from typeguard import TYPE_CHECKING
ImportError: cannot import name 'TYPE_CHECKING' from 'typeguard' (/home/name/miniconda/envs/snncompare/lib/python3.10/site-packages/typeguard/__init__.py)
```

### How can we reproduce the bug?

Create: `mwe.py` with content:
```
from typeguard import TYPE_CHECKING
if TYPE_CHECKING:
    print("Hello world")

@typechecked
def add_two(x:int) -> int:
    """Adds two"""
    return x+2
```
and run:
```bash
pip install typeguard==3.0.2
python mwe.py
```

**Comment by a-t-0** [comment]
After inspecting your repository, I noticed you get `TYPE_CHECKING` using:
```py
from typing import TYPE_CHECKING
```
switching to that removed the error.
