### ISSUE TITLE
Type annotations in string form cause errors while modifying the AST if they use a symbol guarded by TYPE_CHECKING

### ISSUE THREAD

**Issue by johnw-bluemark** [agronholm/typeguard#331]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

4.0.0rc1

### Python version

3.8.10, 3.10.11

### What happened?

```
Traceback (most recent call last):
  File "typecheck.py", line 3, in <module>
    import test_type_checking
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Python38\lib\site-packages\typeguard\_importhook.py", line 106, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "C:\Python38\lib\site-packages\typeguard\_importhook.py", line 83, in source_to_code
    tree = TypeguardTransformer().visit(tree)
  File "C:\Python38\lib\ast.py", line 371, in visit
    return visitor(node)
  File "C:\Python38\lib\site-packages\typeguard\_transformer.py", line 499, in visit_Module
    self.generic_visit(node)
  File "C:\Python38\lib\ast.py", line 447, in generic_visit
    value = self.visit(value)
  File "C:\Python38\lib\ast.py", line 371, in visit
    return visitor(node)
  File "C:\Python38\lib\site-packages\typeguard\_transformer.py", line 595, in visit_FunctionDef
    annotation = self._convert_annotation(copy(arg.annotation))
  File "C:\Python38\lib\site-packages\typeguard\_transformer.py", line 484, in _convert_annotation
    new_annotation = cast(expr, AnnotationTransformer(self).visit(annotation))
  File "C:\Python38\lib\ast.py", line 371, in visit
    return visitor(node)
  File "C:\Python38\lib\site-packages\typeguard\_transformer.py", line 388, in visit_Constant
    return copy_location(new_node.body, node)
AttributeError: 'Expression' object has no attribute 'body'
```

### How can we reproduce the bug?

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from foo import bar

def test(arg: 'bar'):
    pass
```

**Comment by agronholm** [comment]
The fix is available in v4.0.0rc2.

**Comment by AckslD** [comment]
Just fyi if anyone stumbles on this, this only works if the annotation is a string, ie
```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from foo import bar

def test(arg: bar):
    pass
```
does not work

**Comment by agronholm** [comment]
Would you expect it to work, though? Given that `bar` is not available at run time.

**Comment by agronholm** [comment]
At least checking should be skipped if it's not available. I need to investigate why there's a `NameError`.

**Comment by johnw-bluemark** [comment]
That case errors with or without typeguard, so you shouldn't spend too much time on that.

**Comment by agronholm** [comment]
Right, I forgot that there was no `from __future__ import annotations`, so it's all good.

**Comment by AckslD** [comment]
Sorry, my bad! Thanks for the fix and responses :heart:
