### ISSUE TITLE
TypeError: required field "ctx" missing from Subscript

### ISSUE THREAD

**Issue by jolaf** [agronholm/typeguard#332]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

3.0.2

### Python version

3.10.6

### What happened?

```
Traceback (most recent call last):
  File "/media/sf_d/WWPass/git/keymanager/WWPass/KeyManager/test.py", line 4, in <module>
    import_module('A')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/jolaf/.local/lib/python3.10/site-packages/typeguard/_importhook.py", line 96, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "/home/jolaf/.local/lib/python3.10/site-packages/typeguard/_importhook.py", line 85, in source_to_code
    return _call_with_frames_removed(
  File "/home/jolaf/.local/lib/python3.10/site-packages/typeguard/_importhook.py", line 42, in _call_with_frames_removed
    return f(*args, **kwargs)
TypeError: required field "ctx" missing from Subscript
```

### How can we reproduce the bug?

`test.py`:
```python3
from importlib import import_module
from typeguard import install_import_hook
with install_import_hook(('A',)):
    import_module('A')
```

`A.py`:
```python3
def test(*args):
    args = args[0:]
```

Run:
```shell
$ python3 test.py
```

**Comment by agronholm** [comment]
Please try with 4.0.0rc2.

**Comment by jolaf** [comment]
Seems to work fine in 4.0.0rc2, thanks.

When can we expect a pip release?

**Comment by agronholm** [comment]
You mean like [this](https://pypi.org/project/typeguard/4.0.0rc2/)?

**Comment by jolaf** [comment]
Woa, yeah, that's useful, thanks.

But I was thinking more of a 4.0.0 stable release.

**Comment by agronholm** [comment]
> But I was thinking more of a 4.0.0 stable release, as rc2 has problems of its own.

What problems? Have you reported them?
