### ISSUE TITLE
Incorrect issubclass() call

### ISSUE THREAD

**Issue by jolaf** [agronholm/typeguard#334]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

4.0.0rc2 master

### Python version

3.10.6

### What happened?

```
Traceback (most recent call last):
  File "/media/sf_d/WWPass/git/asn1py/test.py", line 4, in <module>
    import_module('A')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/jolaf/git/typeguard/src/typeguard/_importhook.py", line 106, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/media/sf_d/WWPass/git/asn1py/A.py", line 13, in <module>
    A.f()
  File "/media/sf_d/WWPass/git/asn1py/A.py", line 10, in f
    def f(cls: type[T]) -> None:
  File "/home/jolaf/git/typeguard/src/typeguard/_functions.py", line 135, in check_argument_types
    check_type_internal(value, annotation, memo)
  File "/home/jolaf/git/typeguard/src/typeguard/_checkers.py", line 752, in check_type_internal
    checker(value, origin_type, args, memo)
  File "/home/jolaf/git/typeguard/src/typeguard/_checkers.py", line 454, in check_class
    check_typevar(value, expected_class, (), memo, subclass_check=True)
  File "/home/jolaf/git/typeguard/src/typeguard/_checkers.py", line 510, in check_typevar
    check_type_internal(value, annotation, memo)
  File "/home/jolaf/git/typeguard/src/typeguard/_checkers.py", line 752, in check_type_internal
    checker(value, origin_type, args, memo)
  File "/home/jolaf/git/typeguard/src/typeguard/_checkers.py", line 473, in check_class
    elif not issubclass(value, expected_class):
TypeError: issubclass() arg 2 must be a class, a tuple of classes, or a union
```

### How can we reproduce the bug?

`test.py`:
```python3
from importlib import import_module
from typeguard import install_import_hook
with install_import_hook(('A',)):
    import_module('A')
```

`A.py`:
```python3
from typing import Sequence, TypeVar

class V:
    pass

T = TypeVar('T', bound = 'V')

class A:
    @classmethod
    def f(cls: type[T]) -> None:
        pass

A.f()
```

Run:
```shell
$ python3 test.py
```

**Comment by agronholm** [comment]
That typevar is not legal. The `bound` argument must be a concrete class.

**Comment by jolaf** [comment]
You're, I've updated the description.

**Comment by agronholm** [comment]
Can you explain what those annotations are supposed to be doing?

**Comment by agronholm** [comment]
I see you updated the class method, but it makes no sense. How would `cls` ever be a subclass of `V`? And also, you never need to annotate the `cls` (or `self`) parameter anyway.

**Comment by agronholm** [comment]
So the crux of the problem seems to be `bound = 'V'`, specifically the forward reference there. If I replace that with a direct reference to the class `V`, the error goes away.

**Comment by agronholm** [comment]
I was able to reproduce the problem with this:
```python
# dummymodule
T = TypeVar("T", bound="DummyClass")

class DummyClass:
    pass

@typechecked
def typevar_forwardref(x: type[T]) -> T:
    return x()

# test module
def test_typevar_forwardref(dummymodule):
    instance = dummymodule.typevar_forwardref(dummymodule.DummyClass)
    assert isinstance(instance, dummymodule.DummyClass)
```

**Comment by agronholm** [comment]
If you can confirm that the problem is solved for you, I will make another release candidate.

**Comment by jolaf** [comment]
I confirm, problem resolved. Thanks!
