### ISSUE TITLE
Partial forward references can cause runtime errors unrelated to type checking

### ISSUE THREAD

**Issue by johnw-bluemark** [agronholm/typeguard#335]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

4.0.0rc3

### Python version

3.8.10

### What happened?

```
Traceback (most recent call last):
  File "C:\Users\Johnw\Desktop\temp\typecheck.py", line 3, in <module>
    import test
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Python38\lib\site-packages\typeguard\_importhook.py", line 122, in exec_module
    super().exec_module(module)
  File "C:\Users\Johnw\Desktop\temp\test.py", line 3, in <module>
    class foo:
  File "C:\Users\Johnw\Desktop\temp\test.py", line 4, in foo
    def __getattr__(self, attr: str) -> List['foo']:
NameError: name 'foo' is not defined
```

### How can we reproduce the bug?

```
from typing import List

class foo:
    def __getattr__(self, attr: str) -> List['foo']:
        pass
```

**Comment by agronholm** [comment]
Strangely this only happens on Python 3.7 and 3.8.

**Comment by agronholm** [comment]
What is also interesting is that this doesn't get triggered when using `@typechecked`, but only with the import hook.

**Comment by agronholm** [comment]
My hunch was right: the annotation on the function is modified in the process of recompilation. As to why, that's what I'll find out next.

**Comment by agronholm** [comment]
Gotcha: this happened because I was using `copy.copy()` to copy the annotations, and that makes a shallow copy, so any elements nested deeper would get modified. Switching to `copy.deepcopy()` resolved the issue.
