### ISSUE TITLE
Partial forward references that include a type guarded by TYPE_CHECKING will cause errors

### ISSUE THREAD

**Issue by johnw-bluemark** [agronholm/typeguard#336]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

4.0.0rc3

### Python version

3.8.10, 3.10.11

### What happened?

```
Traceback (most recent call last):
  File "C:\Users\Johnw\Desktop\temp\typecheck.py", line 3, in <module>
    import test_type_checking
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Python38\lib\site-packages\typeguard\_importhook.py", line 122, in exec_module
    super().exec_module(module)
  File "C:\Users\Johnw\Desktop\temp\test_type_checking.py", line 6, in <module>
    def test(*args: List['Dict[str, Any]']):
  File "C:\Python38\lib\typing.py", line 261, in inner
    return func(*args, **kwds)
  File "C:\Python38\lib\typing.py", line 370, in __getitem__
    raise TypeError(f"{self} is not subscriptable")
TypeError: typing.Any is not subscriptable
```

### How can we reproduce the bug?

```python
from typing import TYPE_CHECKING, Any, List

if TYPE_CHECKING:
    from typing import Dict

def test(*args: List['Dict[str, Any]']):
    pass
```

**Comment by agronholm** [comment]
This is caused by the replacement of unimportable types with `typing.Any`. What's going wrong is that the subscript is not removed as it should be.
