### ISSUE TITLE
Variadic length tuples are only checked for element at position 0 (possible regression)

### ISSUE THREAD

**Issue by iliapolo** [agronholm/typeguard#476]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

4.3.0

### Python version

Python 3.10.4 (main, Mar 24 2023, 17:14:52) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin

### What happened?

Expected all elements in the tuple to be checked, and for the check typing to fail

### How can we reproduce the bug?

I am in the process of upgrading `typeguard` from 2.13.3 to 4.3.0 and seeing some incorrect behavior.

### `typeguard == 2.13.3`:

```python
from typeguard import check_type
import typing
check_type(argname='arg', value=(1,"2"), expected_type=typing.Tuple[int, ...])
```

Results in:

```console
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/epolon/.virtualenvs/typeguard-test/lib/python3.10/site-packages/typeguard/__init__.py", line 757, in check_type
    checker_func(argname, value, expected_type, memo)
  File "/Users/epolon/.virtualenvs/typeguard-test/lib/python3.10/site-packages/typeguard/__init__.py", line 529, in check_tuple
    check_type('{}[{}]'.format(argname, i), element, element_type, memo)
  File "/Users/epolon/.virtualenvs/typeguard-test/lib/python3.10/site-packages/typeguard/__init__.py", line 785, in check_type
    raise TypeError(
TypeError: type of arg[1] must be int; got str instead

```

This is correct because indeed the second element ("2") is not of type `int`.

### `typeguard == 4.3.0`:

```python
from typeguard import check_type
import typing
check_type(value=(1,"2"), expected_type=typing.Tuple[int, ...])
```

Results in:

```console
(1, '2')
```

This is incorrect. Note that if I use a fixed length tuple instead:

```python
check_type(value=(1,"2"), expected_type=typing.Tuple[int, int])
```

It results in the correct behavior:

```console
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/epolon/.virtualenvs/typeguard-test/lib/python3.10/site-packages/typeguard/_functions.py", line 106, in check_type
    check_type_internal(value, expected_type, memo)
  File "/Users/epolon/.virtualenvs/typeguard-test/lib/python3.10/site-packages/typeguard/_checkers.py", line 861, in check_type_internal
    checker(value, origin_type, args, memo)
  File "/Users/epolon/.virtualenvs/typeguard-test/lib/python3.10/site-packages/typeguard/_checkers.py", line 407, in check_tuple
    check_type_internal(element, element_type, memo)
  File "/Users/epolon/.virtualenvs/typeguard-test/lib/python3.10/site-packages/typeguard/_checkers.py", line 866, in check_type_internal
    raise TypeCheckError(f"is not an instance of {qualified_name(origin_type)}")
typeguard.TypeCheckError: item 1 of tuple is not an instance of int
```

**Comment by agronholm** [comment]
Duplicate issues: https://github.com/agronholm/typeguard/issues/452, https://github.com/agronholm/typeguard/issues/446, https://github.com/agronholm/typeguard/issues/441, https://github.com/agronholm/typeguard/issues/439, https://github.com/agronholm/typeguard/issues/430, https://github.com/agronholm/typeguard/issues/422, https://github.com/agronholm/typeguard/issues/418, https://github.com/agronholm/typeguard/issues/417, https://github.com/agronholm/typeguard/issues/360

Please set `typeguard.config.collection_check_strategy = typeguard.CollectionCheckStrategy.ALL_ITEMS` to check all items in every container.

**Comment by iliapolo** [comment]
@agronholm thanks and apologies for not noticing all those duplicates. I think it might be worth pinning one of these issues so it has higher visibility, as it looks like people are encountering it quite often. Just a suggestion 🤷‍♂️ .
