### ISSUE TITLE
`typing.Literal` can not be correctly checked

### ISSUE THREAD

**Issue by xiaosiyu0603** [agronholm/typeguard#489]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

4.3.0

### Python version

3.11.5

### What happened?

My code:

```python
from typing import *
from typeguard import typechecked


@typechecked
def test(string: Literal["hi"] | Literal['hello']):
    return string


print(test("hi"))
```

Exception raised when running in python:

```log
D:\Home\Desktop>python tgt.py
Traceback (most recent call last):
  File "D:\Home\Desktop\tgt.py", line 11, in <module>
    print(test("hi"))
          ^^^^^^^^^^
  File "D:\Home\Desktop\tgt.py", line 7, in test     
    def test(string: Literal["hi"] | Literal['hello']):
                             ^^^^
NameError: name 'hi' is not defined
```

### How can we reproduce the bug?

Maybe run the code?

**Comment by agronholm** [comment]
This is caused by the wildcard import, the use of which is bad practice. If instead you do:
```py
from typing import Literal
```
This works fine. The underlying problem is that the AST transformer looks for `typing.Literal` and special cases it, but as it can't see where `Literal` comes from, it doesn't special case `Literal`, and ends up removing the quotes.

**Comment by xiaosiyu0603** [comment]
It works well, thanks a lot! 😀🙏

(It's a little hard for python programmers who lack professional background to discover such mistake.😂 Adding some warnings to the documentation might be helpful.)

**Comment by agronholm** [comment]
I'll think about that. This is a shortcoming of the library though, and it could some day be fixed. It wll involve nontrivial amounts of work though.
