### ISSUE TITLE
NamedTuple arguments are not checked by the `@typechecked` annotation?

### ISSUE THREAD

**Issue by kkom** [agronholm/typeguard#49]
First of all, thanks a lot for writing this awesome framework, I find it to be the best way to gradually introducing typing to a Python codebase! I have one problem with it though...

**Problem:** I cannot get arguments that are derived from `NamedTuple` to be checked by the `@typechecked` annotation

**Minimal reproducible example:**

```
from typeguard import typechecked
from typing import NamedTuple

@typechecked
class MyNamedTuple(NamedTuple):
    my_field: str

@typechecked
def print_tuple(t: MyNamedTuple) -> None:
    print("type of the argument is {}, note that it should be {}".format(
        type(t),
        type(MyNamedTuple("example")),
    ))

# this works as it should
t_good = MyNamedTuple('a string')

# this works as it should
print_tuple(t_good)

# BUG: I think this should fail, but it works at runtime!
print_tuple(1)

# just to show that the runtime typechecker sometimes works
t_bad = MyNamedTuple(1)
```

Running it:

```
~ # python3 example.py 
type of the argument is <class '__main__.MyNamedTuple'>, note that it should be <class '__main__.MyNamedTuple'>
type of the argument is <class 'int'>, note that it should be <class '__main__.MyNamedTuple'>
Traceback (most recent call last):
  File "example.py", line 26, in <module>
    t_bad = MyNamedTuple(1)
  File "/usr/local/lib/python3.7/site-packages/typeguard.py", line 493, in wrapper
    check_argument_types(memo)
  File "/usr/local/lib/python3.7/site-packages/typeguard.py", line 462, in check_argument_types
    raise TypeError(exc) from None
TypeError: type of argument "my_field" must be str; got int instead
~ # pip freeze
typeguard==2.2.2
~ # python3 --version
Python 3.7.0
```

Is this a bug, a limitation, or am I using the framework in a wrong way? I would appreciate any kind of help!

Thanks!

Konrad

**Comment by Drino** [comment]
Looks like the typeguard does support only functions decoration - when typechecked decorator is applied to a class, it becomes a simple callable object: 
```
In [1]: from typeguard import typechecked 
   ...: from typing import NamedTuple 
   ...:  
   ...: @typechecked 
   ...: class MyNamedTuple(NamedTuple): 
   ...:     my_field: str 
   ...:  
   ...: t_bad = MyNamedTuple('a') 
   ...:                                                                                                                                                                                                      

In [2]: isinstance(t_bad, MyNamedTuple)                                                                                                                                                                      
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-87ba30959d9b> in <module>
----> 1 isinstance(t_bad, MyNamedTuple)

TypeError: isinstance() arg 2 must be a type or tuple of types

In [3]: isinstance(MyNamedTuple, type)                                                                                                                                                                       
Out[3]: False

In [4]: MyNamedTuple                                                                                                                                                                                        
Out[4]: <function __main__.MyNamedTuple(my_field)>

```

A workaround here may be using the typechecked decorator on __init__, but on NamedTuple this doesn't work (as annotations are not propagated to __new__).

**Comment by agronholm** [comment]
Yeah, nowhere does it say that `@typechecked` has any sort of special handling for classes.

**Comment by kkom** [comment]
Thank you for your responses!

For posterity, annotating `MyNamedTuple` with `@typechecked` actually breaks the runtime typechecker!

I wonder if more people than I would make this mistake, and if it can be prevented? Either by making the typechecker resistant to superflous annotations, or by signalling to the users that classes should not be annotated? 

# Example of good usage

The below piece of code throws the runtime errors as expected:

```
from typeguard import typechecked
from typing import NamedTuple

class MyNamedTuple(NamedTuple):
    my_field: str

@typechecked
def process_tuple(t: MyNamedTuple) -> None:
    print("type of the argument is {}, note that it should be {}".format(
        type(t),
        type(MyNamedTuple("example")),
    ))

process_tuple(1)
```

```
/app # python3 test-typeguard.py 
Traceback (most recent call last):
  File "test-typeguard.py", line 14, in <module>
    process_tuple(1)
  File "/usr/local/lib/python3.7/site-packages/typeguard.py", line 493, in wrapper
    check_argument_types(memo)
  File "/usr/local/lib/python3.7/site-packages/typeguard.py", line 462, in check_argument_types
    raise TypeError(exc) from None
TypeError: type of argument "t" must be a named tuple of type __main__.MyNamedTuple; got int instead
```

# Example of bad usage

However this piece of code renders the typechecker non-working:

```
from typeguard import typechecked
from typing import NamedTuple

@typechecked
class MyNamedTuple(NamedTuple):
    my_field: str

@typechecked
def process_tuple(t: MyNamedTuple) -> None:
    print("type of the argument is {}, note that it should be {}".format(
        type(t),
        type(MyNamedTuple("example")),
    ))

process_tuple(1)
```

```
/app # python3 test-typeguard.py 
type of the argument is <class 'int'>, note that it should be <class '__main__.MyNamedTuple'>
```

**Comment by kkom** [comment]
One more question... After playing with the example code, I just remembered why I decorated the `NamedTuple` with `@typechecked` to get the hacky typechecking of NamedTuple instantiation!

Take a look at the following example:

```
from typeguard import typechecked
from typing import NamedTuple

class MyNamedTuple(NamedTuple):
    my_field: str

def process_tuple_not_typechecked(t: MyNamedTuple) -> None:
    print("sucessfully called the function with argument {} of type {}".format(t, type(t)))

@typechecked
def process_tuple_typechecked(t: MyNamedTuple) -> None:
    print("sucessfully called the function with argument {} of type {}".format(t, type(t)))

t_bad = MyNamedTuple(1)

process_tuple_not_typechecked(t_bad)

process_tuple_typechecked(t_bad)
```

This is the output:

```
/app # python3 test-typeguard.py 
sucessfully called the function with argument MyNamedTuple(my_field=1) of type <class '__main__.MyNamedTuple'>
Traceback (most recent call last):
  File "test-typeguard.py", line 24, in <module>
    process_tuple_typechecked(t_bad)
  File "/usr/local/lib/python3.7/site-packages/typeguard.py", line 493, in wrapper
    check_argument_types(memo)
  File "/usr/local/lib/python3.7/site-packages/typeguard.py", line 462, in check_argument_types
    raise TypeError(exc) from None
TypeError: type of argument "t".my_field must be str; got int instead
```

It is very good that `typeguard` successfully catches the bad call in `process_tuple_typechecked(t_bad)`!

However, I'm still not happy about the fact that `t_bad = MyNamedTuple(1)` succeeds. Certainly, it would be best to catch badly typed data as early in the program as possible.

Such behaviour is most helpful to the programmer -- the exception stack points exactly to where the error is introduced. Also, in the example above, not being able to typecheck the instantiation of `MyNamedTuple` results in the `process_tuple_not_typechecked(t_bad)` call succeeding, which is not ideal either.

@Drino / @agronholm -- any advice on how I could get typechecking on NamedTuple instantiation in a supported way? My intention here is to throw errors as early in the program as possible. Certainly the solution would also need to be maintainable (no copy-pasting of class initiatialization method, etc).

**Comment by agronholm** [comment]
Typeguard only works on type annotated functions, not anything else.

**Comment by agronholm** [comment]
The implementation of NamedTuple is, IIRC, written in C which makes it impossible to check using typeguard or any other library. What you might want to try instead is a static type checker like mypy.

**Comment by kkom** [comment]
> The implementation of NamedTuple is, IIRC, written in C which makes it impossible to check using typeguard or any other library.

The typechecking on construction happens to work, using my totally unfounded and unsupported "method":

```
from typeguard import typechecked
from typing import NamedTuple

class MyNamedTuple(NamedTuple):
    my_str_field: str

@typechecked
class MyHackilyTypecheckedTuple(NamedTuple):
    my_str_field: str

print(MyNamedTuple(my_str_field=1))

print(MyHackilyTypecheckedTuple(my_str_field=1))
```

```
/app # python3 test-typeguard.py 
MyNamedTuple(my_str_field=1)
Traceback (most recent call last):
  File "test-typeguard.py", line 14, in <module>
    print(MyHackilyTypecheckedTuple(my_str_field=1))
  File "/usr/local/lib/python3.7/site-packages/typeguard.py", line 493, in wrapper
    check_argument_types(memo)
  File "/usr/local/lib/python3.7/site-packages/typeguard.py", line 462, in check_argument_types
    raise TypeError(exc) from None
TypeError: type of argument "my_str_field" must be str; got int instead
```

This is why I thought that this could potentially be on the roadmap, and I could try to help with it if it's something that you think would be useful!

Anyways, thanks a lot for your help, things are so much clearer to me right now! Really appreciate your time!
