### ISSUE TITLE
Allow implicit Awaitable for async functions

### ISSUE THREAD

**Issue by koliyo** [agronholm/typeguard#58]
For an API with lots of async functions it becomes a bit messy with `Awaitable` declarations for all return values. Would it be possible to have a flag to allow implicit `Awaitable` for the return type in async functions?

If the function is tagged `async`, the `Awaitable` is a bit redundant and could be inferred by the `async` declaration.

eg

```py
@typechecked
async def foo() -> Awaitable[str]:
    return await getSomeString()
```

could then be written

```py
@typechecked
async def foo() -> str:
    return await getSomeString()
```

**Comment by agronholm** [comment]
The latter form has been standardized as the correct way to declare return value types. If typeguard complains about this, it is wrong and should be fixed.

**Comment by koliyo** [comment]
Example:

```py
from typeguard import typechecked
import asyncio

@typechecked
async def async_test_return_value() -> str:
    return ''

async def main():
    await async_test_return_value()


loop = asyncio.new_event_loop()
loop.run_until_complete(main())
```

```sh
$ python3 typeguard_async.py  
Traceback (most recent call last):
  File "typeguard_async.py", line 13, in <module>
    loop.run_until_complete(main())
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "typeguard_async.py", line 9, in main
    await async_test_return_value()
  File "/usr/local/lib/python3.7/site-packages/typeguard.py", line 495, in wrapper
    check_return_type(retval, memo)
  File "/usr/local/lib/python3.7/site-packages/typeguard.py", line 430, in check_return_type
    raise TypeError(exc) from None
TypeError: type of the return value must be str; got coroutine instead
sys:1: RuntimeWarning: coroutine 'async_test_return_value' was never awaited
```

```sh
$ python3 --version
Python 3.7.2
```

```sh
$ pip3 freeze | grep typeguard
typeguard==2.2.2
```
