### ISSUE TITLE
String annotations of inner classes are not parsed correcly

### ISSUE THREAD

**Issue by jolaf** [agronholm/typeguard#74]
The following code:
```python3
from typeguard import TypeChecker

class Outer:
    class Inner:
        pass

    def f(self) -> 'Inner':
        return self.Inner()

with TypeChecker(('__main__')):
    Outer().f()
    print("OK")
```
fails as follows:
```python3
$ python3 Test.py
/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py:657: UserWarning: the system profiling hook has changed unexpectedly
  warn('the system profiling hook has changed unexpectedly')
Traceback (most recent call last):
  File "Test.py", line 11, in <module>
    Outer().f()
  File "Test.py", line 7, in f
    def f(self) -> 'Inner':
  File "/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py", line 690, in __call__
    memo = self._call_memos[frame] = _CallMemo(func, frame)
  File "/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py", line 55, in __init__
    hints = get_type_hints(func)
  File "/usr/lib/python3.6/typing.py", line 1543, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/usr/lib/python3.6/typing.py", line 350, in _eval_type
    return t._eval_type(globalns, localns)
  File "/usr/lib/python3.6/typing.py", line 245, in _eval_type
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Inner' is not defined
```
It starts working if return type annotation to `f()` is changed to just `Inner` (unquoted), but it breaks tools that are not fully annotation-aware, like `pylint`:
```python3
pylint3 Test.py
************* Module Test
Test.py:7: [E0602(undefined-variable), Outer.f] Undefined variable 'Inner'
```
Everything (`python3`, `pylint`, `mypy`, `typeguard`) works fine if return type annotation to `f()` is changed to `'Outer.Inner'` (quoted), but that doesn't look like a proper solution.

It seems that `'Inner'` (quoted) should work for `typeguard` as soon as plain `Inner` (unquoted) works.

**Comment by jolaf** [comment]
Crashes with import hook as well:
```python3
Traceback (most recent call last):
  File "TG.py", line 5, in <module>
    import Test
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard/importhook.py", line 80, in exec_module
    return super().exec_module(module)
  File "/media/sf_d/WWPass/git/Test.py", line 9, in <module>
    Outer().f()
  File "/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py", line 732, in wrapper
    memo = _CallMemo(func, args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py", line 89, in __init__
    hints = get_type_hints(func)
  File "/usr/lib/python3.6/typing.py", line 1543, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/usr/lib/python3.6/typing.py", line 350, in _eval_type
    return t._eval_type(globalns, localns)
  File "/usr/lib/python3.6/typing.py", line 245, in _eval_type
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Inner' is not defined
```

**Comment by jolaf** [comment]
Confirmed fixed.
