### ISSUE TITLE
Forward references cannot be used with issubclass()

### ISSUE THREAD

**Issue by jolaf** [agronholm/typeguard#75]
The following code:
```python3
from typing import TypeVar

from typeguard import TypeChecker

class A:
    pass

T = TypeVar('T', bound = 'A')

def f(a: T) -> None:
    pass

with TypeChecker('__main__'):
    f(A())
```
displays the following warning:
```python3
$ python3 Test.py
/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py:694: TypeWarning: [MainThread] call to __main__.f() from Test.py:14: Forward references cannot be used with issubclass().
  warn(TypeWarning(memo, event, frame, exc))
```
In `bound` annotation, if `'A'` (quoted) is replaced with `A` (unquoted), the warning disappears.

**Comment by agronholm** [comment]
I have never seen this warning so you will have to provide me a means to produce it.

**Comment by jolaf** [comment]
I'm trying to get one. Probably this helps, here's the line indicating the line in `typeguard` (2.4.1) that causes the warning:

```
py.warnings	WARNING	/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py:694: TypeWarning: [MainThread] call to <method> from <file>.py:152: Forward references cannot be used with issubclass().
  warn(TypeWarning(memo, event, frame, exc))
```

**Comment by jolaf** [comment]
I've finally found the probable cause. Updated the issue.

**Comment by agronholm** [comment]
I'm not sure how I should fix this. The `_ForwardRef` class is not part of the public interface of the typing module.

**Comment by agronholm** [comment]
Hm, there is `typing.ForwardRef` that is public, maybe that is something I could check against?

**Comment by agronholm** [comment]
It's only in 3.7 onwards though.

**Comment by agronholm** [comment]
On earlier versions I could just import `_ForwardRef` since they seem to be pretty much the same thing.

**Comment by jolaf** [comment]
Crashes with import hook as well.
```python3
from typeguard.importhook import install_import_hook

install_import_hook('Test')

import Test
```
```python3
from typing import TypeVar

class A:
    pass

T = TypeVar('T', bound = 'A')

def f(a: T) -> None:
    pass

f(A())
```
```python3
$ python3 TypeGuardTest.py 
Traceback (most recent call last):
  File "TypeGuardTest.py", line 5, in <module>
    import Test
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard/importhook.py", line 80, in exec_module
    return super().exec_module(module)
  File "/media/sf_d/WWPass/git/Test.py", line 11, in <module>
    f(A())
  File "/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py", line 733, in wrapper
    check_argument_types(memo)
  File "/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py", line 616, in check_argument_types
    raise exc from None
  File "/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py", line 614, in check_argument_types
    check_type(description, value, expected_type, memo)
  File "/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py", line 547, in check_type
    check_typevar(argname, value, expected_type, memo)
  File "/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py", line 407, in check_typevar
    if not issubclass(value_type, bound_type):
  File "/usr/lib/python3.6/typing.py", line 263, in __subclasscheck__
    raise TypeError("Forward references cannot be used with issubclass().")
TypeError: Forward references cannot be used with issubclass().
```

**Comment by agronholm** [comment]
I cannot reproduce this anymore with latest master. Can you confirm that it's fixed?

**Comment by agronholm** [comment]
Never mind, problem with the test module.

**Comment by jolaf** [comment]
Still actual for the current master, da05d39
