### ISSUE TITLE
Occasional error in weakref

### ISSUE THREAD

**Issue by youknowone** [agronholm/typeguard#8]
I
```
Exception ignored in: <function _removeHandlerRef at 0x10b2e8620>
Traceback (most recent call last):
  File "/Users/username/.pyenv/versions/3.6.0/lib/python3.6/logging/__init__.py", line 728, in _removeHandlerRef
  File "/Users/username/venv/lib/python3.6/site-packages/typeguard.py", line 589, in __call__
  File "/Users/username/venv/lib/python3.6/site-packages/typeguard.py", line 81, in find_function
  File "/Users/username/venv/lib/python3.6/weakref.py", line 400, in get
TypeError: 'NoneType' object is not callable
```

**Comment by youknowone** [comment]
Attaching test code: [test.zip](https://github.com/agronholm/typeguard/files/684342/test.zip)

Shell command:
```
$ python --version
Python 3.6.0
$ python typeguard_test.py
```

**Comment by obadz** [comment]
@agronholm, are you sure this is fixed?

Am still seeing these errors in 2.1.3:

```
============================= test session starts ==============================
platform linux -- Python 3.5.3, pytest-3.0.6, py-1.4.31, pluggy-0.4.0
rootdir: /tmp/nix-build-python3.5-typeguard-2.1.3.drv-0/typeguard-2.1.3, inifile: setup.cfg
collected 112 items

tests/test_typeguard.py ................................................................................................................

========================== 112 passed in 0.47 seconds ==========================
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7ffff3495ae8>
Traceback (most recent call last):
  File "/nix/store/76rgpkm1jqgqwz4bjnk8y37z29q82zgy-python3-3.5.3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7ffff3495ae8>
Traceback (most recent call last):
  File "/nix/store/76rgpkm1jqgqwz4bjnk8y37z29q82zgy-python3-3.5.3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7ffff3495ae8>
Traceback (most recent call last):
  File "/nix/store/76rgpkm1jqgqwz4bjnk8y37z29q82zgy-python3-3.5.3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
/nix/store/2b8jvmvv1xp0pprx767v8jjby0q67pax-python3.5-typeguard-2.1.3
```

See also: https://github.com/NixOS/nixpkgs/pull/25040#issuecomment-295915477

**Comment by agronholm** [comment]
I have no idea what might be causing these. Do you mind doing some research? I'm kinda busy with other things now.
