### ISSUE TITLE
Yield type inferred incorrectly in nested Generators

### ISSUE THREAD

**Issue by jolaf** [agronholm/typeguard#81]
The following code:
```python3
from typing import Generator

from typeguard import TypeChecker

def a() -> Generator[str, None, None]:
    yield "OK"

def b() -> Generator[Generator[str, None, None], None, None]:
    yield a()
    yield a()

with TypeChecker('__main__'):
    for f in b():
        print(next(f))
```
produces the following output:
```python3
$ python3 Test.py 
OK
/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py:932: TypeWarning: [MainThread] return from __main__.b() at Test.py:10: type of yielded value must be str; got generator instead
  warn(TypeWarning(memo, event, frame, exc))
OK
```
Note that the problem occurs only at the second `yield`, but not at the first one.

This is an old issue that I'm observing for some time, but I thought it to be a consequence of #77, but #77 is fixed now in v2.5.1, but this issue still persists.

**Comment by jolaf** [comment]
```python3
$ python3 --version
Python 3.6.8
```

**Comment by agronholm** [comment]
Using `@typechecked` instead gives another unexpected error: `TypeError: type of value yielded from generator must be collections.abc.Generator; got typeguard.TypeCheckedGenerator instead`
I guess I need to implicitly inherit from (or register with `collections.abc.Generator`) the `TypeCheckedGenerator` class?

**Comment by jolaf** [comment]
Note that the problem persists if `a()` is typed as `Iterator` instead.

**Comment by agronholm** [comment]
> Note that the problem persists if `a()` is typed as `Iterator[str]` instead.

Which seems strange because I didn't register `TypeCheckedGenerator` as an `Iterator` either. What am I missing here?

**Comment by agronholm** [comment]
Oh, sorry, I misread your post.

**Comment by agronholm** [comment]
What I meant to say is that this works:
```python3
from typing import Generator, Iterator

from typeguard import typechecked


@typechecked
def a() -> Iterator[str]:
    yield "OK"


@typechecked
def b() -> Generator[Iterator[str], None, None]:
    yield a()
    yield a()


for f in b():
    print(f.send(None))

```

**Comment by jolaf** [comment]
Crashes with import hook as well.

`TypeGuardTest.py`:
```python3
from typeguard.importhook import install_import_hook

install_import_hook('Test')

import Test
```
`Test.py`:
```python3
$ python3 TypeGuardTest.py 
Traceback (most recent call last):
  File "TypeGuardTest.py", line 5, in <module>
    import Test
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard/importhook.py", line 80, in exec_module
    return super().exec_module(module)
  File "/media/sf_d/WWPass/git/Test.py", line 10, in <module>
    for f in b():
  File "/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py", line 635, in __next__
    return self.send(None)
  File "/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py", line 652, in send
    check_type('value yielded from generator', value, self.__yield_type, memo=self.__memo)
  File "/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py", line 516, in check_type
    check_type(argname, value, origin_type, memo)
  File "/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py", line 544, in check_type
    format(argname, qualified_name(expected_type), qualified_name(value)))
TypeError: type of value yielded from generator must be collections.abc.Generator; got typeguard.TypeCheckedGenerator instead
```
```python3
$ python3 TypeGuardTest.py 
Traceback (most recent call last):
  File "TypeGuardTest.py", line 5, in <module>
    import Test
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard/importhook.py", line 80, in exec_module
    return super().exec_module(module)
  File "/media/sf_d/WWPass/git/Test.py", line 8, in <module>
    Outer().f()
  File "/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py", line 732, in wrapper
    memo = _CallMemo(func, args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py", line 89, in __init__
    hints = get_type_hints(func)
  File "/usr/lib/python3.6/typing.py", line 1543, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/usr/lib/python3.6/typing.py", line 350, in _eval_type
    return t._eval_type(globalns, localns)
  File "/usr/lib/python3.6/typing.py", line 245, in _eval_type
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Inner' is not defined
```

**Comment by jolaf** [comment]
This issue seems to be a real blocker for me, preventing me from running my full-scale software under typeguard with import hook. :(

**Comment by agronholm** [comment]
I've fixed this locally and I will soon push the changes once the tests and everything check out.

**Comment by agronholm** [comment]
This fixes generators for `@typechecked`. If it's still broken with the profiler hook, I frankly don't care.

**Comment by jolaf** [comment]
Okay, but it crashes with import hook too.
https://github.com/agronholm/typeguard/issues/81#issuecomment-551336446

**Comment by agronholm** [comment]
Have you tested against the fix I made? The example code in the comment does work for me now.

**Comment by jolaf** [comment]
Yes, looks fixed, thanks!
