### ISSUE TITLE
absolute_import error when importing a namespace package

### ISSUE THREAD

**Issue by jolaf** [agronholm/typeguard#87]
The following code:

`Test.py`:
```python3
from typeguard.importhook import install_import_hook, TypeguardFinder

class AllModulesFinder(TypeguardFinder):
    def should_instrument(self, moduleName: str) -> bool:
        return True

install_import_hook('', cls = AllModulesFinder)

import A
```

`A/__init__.py`:
```python3
__import__('pkg_resources').declare_namespace(__name__)
```
produces the following output:
```python3
$ python3 Test.py
Traceback (most recent call last):
  File "Test.py", line 9, in <module>
    import A
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard/importhook.py", line 80, in exec_module
    return super().exec_module(module)
  File "A/__init__.py", line 1, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard/importhook.py", line 80, in exec_module
    return super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "/usr/local/lib/python3.6/dist-packages/typeguard/importhook.py", line 75, in source_to_code
    dont_inherit=True, optimize=_optimize)
  File "/usr/local/lib/python3.6/dist-packages/typeguard/importhook.py", line 14, in _call_with_frames_removed
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 18
    from __future__ import absolute_import
    ^
SyntaxError: from __future__ imports must occur at the beginning of the file
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard/importhook.py", line 80, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard/importhook.py", line 80, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3/dist-packages/apport/report.py", line 28, in <module>
    import problem_report
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard/importhook.py", line 80, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3/dist-packages/problem_report.py", line 16, in <module>
    from email.mime.multipart import MIMEMultipart
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard/importhook.py", line 80, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3.6/email/mime/multipart.py", line 9, in <module>
    from email.mime.base import MIMEBase
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard/importhook.py", line 80, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3.6/email/mime/base.py", line 9, in <module>
    import email.policy
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard/importhook.py", line 80, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3.6/email/policy.py", line 26, in <module>
    class EmailPolicy(Policy):
  File "/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py", line 721, in typechecked
    if callable(attr) and attr.__qualname__.startswith(prefix):
AttributeError: 'HeaderRegistry' object has no attribute '__qualname__'

Original exception was:
Traceback (most recent call last):
  File "Test.py", line 9, in <module>
    import A
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard/importhook.py", line 80, in exec_module
    return super().exec_module(module)
  File "A/__init__.py", line 1, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard/importhook.py", line 80, in exec_module
    return super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "/usr/local/lib/python3.6/dist-packages/typeguard/importhook.py", line 75, in source_to_code
    dont_inherit=True, optimize=_optimize)
  File "/usr/local/lib/python3.6/dist-packages/typeguard/importhook.py", line 14, in _call_with_frames_removed
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 18
    from __future__ import absolute_import
    ^
SyntaxError: from __future__ imports must occur at the beginning of the file
```

Python 3.6.8, typeguard 2.6.0

**Comment by jolaf** [comment]
Starts working normally if `should_instrument()` code is changed to:
```python3
return moduleName != 'pkg_resources'
```

**Comment by jolaf** [comment]
Starts working normally if `should_instrument()` code is changed to:
```python3
        return not moduleName.startswith('pkg_resources')
```

**Comment by agronholm** [comment]
The dummy module I use for testing has this very import in it and that works fine.

**Comment by agronholm** [comment]
I doubt this has anything to do with the namespace packages.

**Comment by agronholm** [comment]
I was able to reproduce the error, however.

**Comment by agronholm** [comment]
The error occurs when simply importing `pkg_resources` with the import hook active.

**Comment by agronholm** [comment]
This happens because of the module docstring that comes before the future imports.

**Comment by jolaf** [comment]
Confirmed fixed.

**Comment by jolaf** [comment]
Fails as follows on current `master` (@d6d14cf):
```python3
$ python3 Test.py 
Traceback (most recent call last):
  File "Test.py", line 9, in <module>
    import A
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/media/sf_d/WWPass/git/common/A/__init__.py", line 1, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 77, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/lib/python3/dist-packages/pkg_resources/extern/__init__.py", line 43, in load_module
    __import__(extant)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 5353, in <module>
    class pyparsing_common:
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/__init__.py", line 721, in typechecked
    if callable(attr) and attr.__qualname__.startswith(prefix):
AttributeError: 'Combine' object has no attribute '__qualname__'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3/dist-packages/apport/report.py", line 28, in <module>
    import problem_report
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3/dist-packages/problem_report.py", line 16, in <module>
    from email.mime.multipart import MIMEMultipart
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3.6/email/mime/multipart.py", line 9, in <module>
    from email.mime.base import MIMEBase
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3.6/email/mime/base.py", line 9, in <module>
    import email.policy
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3.6/email/policy.py", line 26, in <module>
    class EmailPolicy(Policy):
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/__init__.py", line 721, in typechecked
    if callable(attr) and attr.__qualname__.startswith(prefix):
AttributeError: 'HeaderRegistry' object has no attribute '__qualname__'

Original exception was:
Traceback (most recent call last):
  File "Test.py", line 9, in <module>
    import A
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/media/sf_d/WWPass/git/common/A/__init__.py", line 1, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 77, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/lib/python3/dist-packages/pkg_resources/extern/__init__.py", line 43, in load_module
    __import__(extant)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 5353, in <module>
    class pyparsing_common:
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/__init__.py", line 721, in typechecked
    if callable(attr) and attr.__qualname__.startswith(prefix):
AttributeError: 'Combine' object has no attribute '__qualname__'
```

**Comment by agronholm** [comment]
This looks like a totally different issue and has nothing whatsoever to do with either the module docstring or namespace packages.

**Comment by jolaf** [comment]
Okay, filed #90.
