### ISSUE TITLE
Import hook doesn't work with metaclasses

### ISSUE THREAD

**Issue by jolaf** [agronholm/typeguard#88]
The following code:

`TypeGuardTest.py`:
```python3
from typeguard.importhook import install_import_hook

install_import_hook('Test')

import Test
```

`Test.py`:
```python3
class Metaclass(type):
    pass

class Class(metaclass = Metaclass):
    def f(self) -> None:
        print("OK")

Class().f()
```
produces the following output:
```python3
$ python3 TypeGuardTest.py 
Traceback (most recent call last):
  File "TypeGuardTest.py", line 5, in <module>
    import Test
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard/importhook.py", line 80, in exec_module
    return super().exec_module(module)
  File "Test.py", line 1, in <module>
    class Metaclass(type):
  File "/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py", line 720, in typechecked
    attr = getattr(func, key)
AttributeError: __abstractmethods__
```

**Comment by jolaf** [comment]
Confirmed fixed.
