### ISSUE TITLE
Import hook fails on @functools.lru_cache

### ISSUE THREAD

**Issue by jolaf** [agronholm/typeguard#89]
The following code:

`TypeGuardTest.py`:
```python3
from typeguard.importhook import install_import_hook

install_import_hook('Test')

import Test
```

`Test.py`:
```python3
from functools import lru_cache

@lru_cache()
def f() -> None:
    print("OK")

f()
```
produces the following output:
```python3
$ python3 Test.py 
OK
$ python3 TypeGuardTest.py 
Traceback (most recent call last):
  File "TypeGuardTest.py", line 5, in <module>
    import Test
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard/importhook.py", line 80, in exec_module
    return super().exec_module(module)
  File "Test.py", line 4, in <module>
    def f() -> None:
  File "/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py", line 759, in typechecked
    if func.__code__ is not wrapper.__code__:
AttributeError: 'functools._lru_cache_wrapper' object has no attribute '__code__'
```

**Comment by jolaf** [comment]
Confirmed fixed.
