### ISSUE TITLE
Import hook crashes on pkg_resources

### ISSUE THREAD

**Issue by jolaf** [agronholm/typeguard#90]
The following code:
```python3
from typeguard.importhook import install_import_hook

install_import_hook('')

import pkg_resources
```
produces the following output:
```python3
$ python3 Test.py 
Traceback (most recent call last):
  File "Test.py", line 5, in <module>
    import pkg_resources
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 77, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/lib/python3/dist-packages/pkg_resources/extern/__init__.py", line 43, in load_module
    __import__(extant)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 5353, in <module>
    class pyparsing_common:
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/__init__.py", line 721, in typechecked
    if callable(attr) and attr.__qualname__.startswith(prefix):
AttributeError: 'Combine' object has no attribute '__qualname__'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3/dist-packages/apport/report.py", line 28, in <module>
    import problem_report
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3/dist-packages/problem_report.py", line 16, in <module>
    from email.mime.multipart import MIMEMultipart
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3.6/email/mime/multipart.py", line 9, in <module>
    from email.mime.base import MIMEBase
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3.6/email/mime/base.py", line 9, in <module>
    import email.policy
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3.6/email/policy.py", line 26, in <module>
    class EmailPolicy(Policy):
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/__init__.py", line 721, in typechecked
    if callable(attr) and attr.__qualname__.startswith(prefix):
AttributeError: 'HeaderRegistry' object has no attribute '__qualname__'

Original exception was:
Traceback (most recent call last):
  File "Test.py", line 5, in <module>
    import pkg_resources
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 77, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/lib/python3/dist-packages/pkg_resources/extern/__init__.py", line 43, in load_module
    __import__(extant)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 5353, in <module>
    class pyparsing_common:
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/__init__.py", line 721, in typechecked
    if callable(attr) and attr.__qualname__.startswith(prefix):
AttributeError: 'Combine' object has no attribute '__qualname__'
```

**Comment by jolaf** [comment]
Wow, I'm getting a lot of warnings like
`UserWarning: no type annotations present -- not typechecking pkg_resources.Distribution._filter_extras`
That's amazing!

**Comment by jolaf** [comment]
In fact, that's what I actually get, fully:
```python3
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking zipfile.ZipInfo.from_file
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking zipfile.ZipFile._sanitize_windows_name
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking datetime.timedelta.__new__
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking datetime.date.__new__
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking datetime.date.fromtimestamp
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking datetime.date.today
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking datetime.date.fromordinal
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking datetime.time.__new__
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking datetime.datetime.__new__
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking datetime.datetime._fromtimestamp
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking datetime.datetime.fromtimestamp
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking datetime.datetime.utcfromtimestamp
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking datetime.datetime.now
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking datetime.datetime.utcnow
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking datetime.datetime.combine
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking datetime.datetime.strptime
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking datetime.timezone.__new__
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking datetime.timezone._create
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking datetime.timezone._name_from_offset
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking plistlib.Plist.fromFile
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking plistlib.Data.fromBase64
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking tempfile.TemporaryDirectory._cleanup
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources.extern.packaging._compat.with_metaclass.<locals>.metaclass.__new__
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources._vendor.pyparsing.ParseBaseException._from_exception
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources._vendor.pyparsing.ParseResults.__new__
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources._vendor.pyparsing.ParserElement.setDefaultWhitespaceChars
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources._vendor.pyparsing.ParserElement.inlineLiteralsUsing
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources._vendor.pyparsing.ParserElement.resetCache
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources._vendor.pyparsing.ParserElement.enablePackrat
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources._vendor.pyparsing.Keyword.setDefaultKeywordChars
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources._vendor.pyparsing.pyparsing_common.convertToDate
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources._vendor.pyparsing.pyparsing_common.convertToDatetime
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources._vendor.pyparsing.pyparsing_common.stripHTMLTags
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources._vendor.pyparsing.tokenMap.<locals>.pa
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources.WorkingSet._build_master
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources.WorkingSet._build_from_requirements
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources.ResourceManager._warn_unsafe_extraction_path
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources.DefaultProvider._register
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources.ZipManifests.build
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources.ZipProvider._get_date_and_size
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources.EntryPoint.parse
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources.EntryPoint._parse_extras
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources.EntryPoint.parse_group
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources.EntryPoint.parse_map
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources.Distribution.from_location
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources.Distribution._filter_extras
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources.Distribution.from_filename
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post11-py3.6.egg/typeguard/__init__.py:753: UserWarning: no type annotations present -- not typechecking pkg_resources.Requirement.parse
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
```

**Comment by jolaf** [comment]
And the test passes.

**Comment by jolaf** [comment]
The warnings seem relevant, so they're probably not a problem.
If they're not needed, they can be filtered out with `warnings.filterwarnings()` or the module causing problem can be excluded from checking by custom `TypeguardFinder`.

**Comment by jolaf** [comment]
Is it a correct behavior that `install_import_hook('')` really checks **everything**?

**Comment by jolaf** [comment]
Can those `UserWarning`s be changed into `TypeWarning`s for consistency?

**Comment by agronholm** [comment]
I'm surprised you are getting all those warnings because the import hook should only be installing the decorator on functions that have annotations, or classes (in which case it also checks if the methods have annotations). Can you show me an example where you get this warning where you should not?

**Comment by agronholm** [comment]
Never mind, the warning list you provided tells me what to look for. I still don't get why you're trying to instrument *everything*. What is the point of trying to instrument the standard library, or third party libs?

**Comment by agronholm** [comment]
> Is it an intended behavior that `install_import_hook('')` really checks _everything_?

Why did you expect anything different? Having an empty prefix means that every module loaded from then on gets instrumented.

**Comment by jolaf** [comment]
> Can you show me an example where you get this warning where you should not?

I'm just running the test from this issue on the latest master, `da05d39`.

**Comment by jolaf** [comment]
> why you're trying to instrument _everything_.

I'm just lazy to specify a list of packages to check.
Sounds like a reasonable reason to me. :)

Also, I'm using a single "typeguard runner" script to check all my projects, and I don't like the idea of having to customize it for each project.

> What is the point of trying to instrument the standard library, or third party libs?

Most of all, I'd like to make sure that I'm doing the system calls correctly, according to type annotations.

Also, I'm helping `typeshed` project a bit, and I'm hoping `typeguard` could help me with identifying gaps in the stubs.

**Comment by jolaf** [comment]
> Having an empty prefix means that every module loaded from then on gets instrumented.

I'm just being stupid, sorry. :)

**Comment by agronholm** [comment]
> Also, I'm helping typeshed project a bit, and I'm hoping typeguard could help me with identifying gaps in the stubs.

There are tools more suited to that than typeguard, such as [MonkeyType](https://pypi.org/project/MonkeyType/). I recall that Guido also made a project to that end but I can't recall its name.

**Comment by agronholm** [comment]
I've now fixed the warnings.

**Comment by jolaf** [comment]
Confirmed, I see no warnings now.

I'd prefer them to stay but be converted into `TypeWarning`s, but well, what to do.

**Comment by agronholm** [comment]
But why? The point of the warning was to inform the user that they're using `@typechecked` incorrectly. It makes zero sense to emit them with the import hook which installs those decorators implicitly.

**Comment by jolaf** [comment]
I saw those warnings like "Be advised, that this particular package that you indicated that you want to type check, has no typing information and thus no errors would be reported from the code in it".

This can be relevant not only for standart library, but for user's code also, like if the user forgot to include `py.typed` file into their package.
