### ISSUE TITLE
*args is not flexible enough

### ISSUE THREAD

**Issue by jolaf** [agronholm/typeguard#91]
The following code:

`TypeGuardTest.py`:
```python3
from typeguard.importhook import install_import_hook

install_import_hook('Test')

import Test
```

`Test.py`:
```python3
class A:
    def __init__(self, x: int, y: str):
        print("OK")

    @classmethod
    def f(cls, *args) -> 'A':
        return cls(*args)

class B(A):
    def __init__(self, y: str):
        super().__init__(111, y)

B.f('abc')
```
produces the following output:
```python3
$ python3 Test.py
OK
$ python3 TypeGuardTest.py
Traceback (most recent call last):
  File "TypeGuardTest.py", line 5, in <module>
    import Test
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/importhook.py", line 82, in exec_module
    return super().exec_module(module)
  File "Test.py", line 13, in <module>
    B.f('abc')
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/__init__.py", line 737, in wrapper
    retval = func(*args, **kwargs)
  File "Test.py", line 7, in f
    return cls(*args)
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/__init__.py", line 735, in wrapper
    memo = _CallMemo(python_func, args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.6/dist-packages/typeguard-2.6.0.post5-py3.6.egg/typeguard/__init__.py", line 80, in __init__
    self.arguments = self.signature.bind(*args, **kwargs).arguments
  File "/usr/lib/python3.6/inspect.py", line 2997, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/usr/lib/python3.6/inspect.py", line 2912, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'y'
```

On `master` branch, d6d14cf.

**Comment by jolaf** [comment]
The return type annotation to `A.f()` seems critical.
If it is removed, the problem disappears.

**Comment by agronholm** [comment]
I was unable to reproduce this on latest master. Would you mind testing again?

**Comment by agronholm** [comment]
Never mind, my test module had an error in it.

**Comment by agronholm** [comment]
For some reason, the wrapper for `A.__init__()` gets called first. I'm trying to figure out why.

**Comment by agronholm** [comment]
if I call `B(*args)` instead in `A.f()`, or if I decorate the constructors individually, then it works as expected. I cannot comprehend why this is happening.

**Comment by agronholm** [comment]
Actually, `cls` points to the `A` class if I decorate the class with `@typechecked`, but `B` if I don't. Now I have to figure out why *that* is happing.

**Comment by agronholm** [comment]
This snippet demonstrates the issue. If you have any clue on how to fix this, I'm all ears:
```python3
from functools import wraps


class A:
    @classmethod
    def method(cls):
        print('cls = %s' % cls.__name__)


class B(A):
    pass


def wrapper(func):
    @wraps(func)
    def inner(*args, **kwargs):
        return func(*args, **kwargs)

    return inner


A.method = wrapper(A.method)
B.method()
```

**Comment by jolaf** [comment]
Confirmed fixed.
